## 02. numpy

### 2-1. numpy 배열 연산

In [2]:
import numpy as np

In [5]:
# 배열 간 연산 (1차원)
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 - a2)

[5 7 9]
[-3 -3 -3]


In [6]:
# 배열 간 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)

print(a1)
print(a2)
print(a1 + a2)
print(a2 - a1)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[10 10]
 [10 10]]


In [7]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1,2,3,4])
print(a1 + 10)
print(a1 * 2)

[11 12 13 14]
[2 4 6 8]


In [8]:
# 배열과 스칼라 연산 (2차원)
a1 = np.arange(1, 5).reshape(2, 2)
a2 = np.arange(11, 15).reshape(2, 2)
print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [10]:
# 배열의 구조가 다를 경우
a1 = np.array([1,2])
a2 = np.array([1,2,3])
# print(a1 + a2) # ValueError

In [11]:
# 브로드캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1, 2, 3],
                [4, 5, 6]]) # (2, 3)
a2 = np.array([10, 20, 30]) # 길이가 3인 1차원 배열 (3, )

# 1치원 길이 3
[10, 20, 30]

# 2차원으로 변형 (1, 3)
[[10, 20, 30]]

# 2차원의 행이 2 -> 2로 확장
[[10, 20, 30],
 [10, 20, 30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [ ]:
# 브로드캐스팅 예제
a1 = np.array([[1],[2],[3]]) # (3, 1)
a2 = np.array([10, 20, 30]) # (3, )

# a2 : (3, ) -> (1, 3) 변형
[[10,20,30]]

# a1과 a2 비교 ->  (3, 1), (1, 3)
[[1,1,1],[2,2,2],[3,3,3]]
[[10,20,30], [10,20,30], [10,20,30]]

print(a1 + a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
