## 03. NumPy
### 3-1. 배열의 형태 변형과 차원 확장/축소

In [79]:
import numpy as np

In [6]:
# array.ravel()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 view로 반환 (view 변경 시 원본도 변경)

a = np.array([[1,2,3], [4,5,6]])
print(a)

flat = a.ravel()
print(flat)

flat[2] = 100
print(flat)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[  1   2 100   4   5   6]
[[  1   2 100]
 [  4   5   6]]


In [ ]:
# array.flatten()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 복사본으로 반환 (복사본 변경 시 원본은 변경되지 않음)

a = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(a)

flat = a.flatten()
print(flat)

flat[4] = 0
print(flat)
print(a)  # 기존의 것은 바뀌지 않음(복사본)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 0 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1

a = np.array([[1,2,3], [4,5,6]])
print("원본:", a.shape)

# axis = 0

a0 = np.expand_dims(a, axis = 0)
print("a0", a0.shape)
print("a0", a0)

# axis = 1

a1 = np.expand_dims(a, axis = 1)
print("a1", a1.shape)
print("a1", a1)

# axis = 2

a2 = np.expand_dims(a, axis = 2)
print("a2", a2.shape)
print("a2", a2)

원본: (2, 3)
a0 (1, 2, 3)
a0 [[[1 2 3]
  [4 5 6]]]
a1 (2, 1, 3)
a1 [[[1 2 3]]

 [[4 5 6]]]
a2 (2, 3, 1)
a2 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# np.squeeze(a, axis)
# - 배열에서 크기가 1인 차원을 제거해주는 함수 (차원 축소)

a = np.array([
    [ [[1],[2],[3]] ],
    [ [[1],[2],[3]] ]
])
print(a.shape) # (2, 1, 3, 1)

s = np.squeeze(a)
print(s)
print(s.shape)

(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [19]:
# axis 지정하는 경우

a2 = np.zeros((1,4,1,2))
print(a2.shape)

s1 = np.squeeze(a2, axis = 0)
print(s1.shape) # (4, 1, 2)

s2 = np.squeeze(a2, axis = 2)
print(s2.shape) # (1, 4, 2)


# 차원의 크기가 1이 아닌 차원은 제거할 수 없음

# s3 = np.squeeze(a2,axis=1) # ValueError

(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


In [22]:
# np.unique()
# - 배열에서 중복된 요소를 제거

a = np.array([1,1,1,5,5,2,2,2,2,4,4,4,3,3,3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1) # [1 2 3 4 5]

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스:", idx)
print("원본의 고유값 인덱스:", inv)
print("값의 등장 횟수:", cnt)

[1 2 3 4 5]
인덱스: [ 0  5 12  9  3]
원본의 고유값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수: [3 4 3 3 2]


#### 실습 1. 배열 형태 변형, 차원 확장 축소(1)

In [48]:
#  1.아래의 배열을 사용해서
# arr= np.array([[10, 20], [30, 40], [50, 60]])
# 1. ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
# 2. arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 
# ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인하세요

arr= np.array([[10, 20], [30, 40], [50, 60]])
r = arr.ravel()
f = arr.flatten()
print("ravel:", r)
print("flatten", f)

arr[0, 0] = 999
print("ravel 결과:", r)
print("flatten 결과", f)



ravel: [10 20 30 40 50 60]
flatten [10 20 30 40 50 60]
ravel 결과: [999  20  30  40  50  60]
flatten 결과 [10 20 30 40 50 60]


In [49]:
# 2.크기가 32x32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여 
# shape (1, 32, 32)로 바꾸는 코드를 작성하세요.
# img= np.random.rand(32, 32)

img= np.random.rand(32, 32)
img_expanded = np.expand_dims(img, axis = 0)
print(img_expanded)
print(img_expanded.shape)


[[[0.80348014 0.42152338 0.22370952 ... 0.61794404 0.94039835 0.3630018 ]
  [0.26290144 0.78636192 0.44466584 ... 0.13953882 0.73693257 0.913183  ]
  [0.07591251 0.94624447 0.72413922 ... 0.83432692 0.19548497 0.03073146]
  ...
  [0.87693753 0.13116704 0.40115404 ... 0.0884239  0.8308931  0.77864363]
  [0.18768126 0.11854806 0.22367341 ... 0.20553299 0.20997426 0.0228001 ]
  [0.00529381 0.04330225 0.82325776 ... 0.87537229 0.80575854 0.4912741 ]]]
(1, 32, 32)


#### 실습 1. 배열 형태 변형, 차원 확장 축소(2)

In [29]:
# 3.아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
# img= np.random.randint(0, 255, (1, 28, 28, 1))

img= np.random.randint(0, 255, (1, 28, 28, 1))
img_squeeze = np.squeeze(img)
print(img_squeeze.shape)

(28, 28)


In [50]:
#  4.아래 2차원 배열을 1) 1차원 배열로 만든 후 2) 중복값을 제거한 뒤 
# shape (1, n)으로 재구성하세요.
# arr= np.array([[3, 1, 2, 2],
#                [1, 2, 3, 1],
#                [2, 2, 1, 4]]

arr= np.array([[3, 1, 2, 2],
                [1, 2, 3, 1],
                [2, 2, 1, 4]])
flat = arr.flatten()
print("1차원 배열:", flat)
uniq = np.unique(flat)
print("중복값 제거:", uniq)
result = uniq.reshape(1, -1) # -1을 입력할시 자동으로 계산해줌
print("재구성", result)
print("shape:", result.shape)

1차원 배열: [3 1 2 2 1 2 3 1 2 2 1 4]
중복값 제거: [1 2 3 4]
재구성 [[1 2 3 4]]
shape: (1, 4)


#### 실습 1. 배열 형태 변형, 차원 확장 축소(3)

In [ ]:
# 5.다음 배열을 shape (10,)로 만든 뒤 고유값배열을 구하세요.
# arr= np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]])  # shape (1, 10, 1)

arr= np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]]) 

arr_squeeze = np.squeeze(arr)
print("1차원 배열:", arr_squeeze)

uniq = np.unique(flat)
print("고유값 배열:", uniq)

1차원 배열: [1 3 2 1 3 2 3 1 2 3]
고유값 배열: [1 2 3]


In [53]:
# 6.다음 배열을 1차원 배열로 만든 후 고유값만 추출해서 
# shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
# arr= np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]], [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ])  # shape (2, 3, 4)

arr = np.array([
    [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
    [[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ]) 

arr1d = arr.flatten()
print("1차원 배열:", arr1d)

uniq = np.unique(arr1d)
print("고유값:", uniq)

reshaped = np.expand_dims(uniq, axis = 1)
print("2차원 배열 변환:\n", reshaped)
print(reshaped.shape)

1차원 배열: [0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]
고유값: [0 1 2 3 4 5 6 7 8]
2차원 배열 변환:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(9, 1)


### 3-2. 배열의 결합과 분리

In [57]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합

a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

result1 = np.concatenate((a, b), axis = 0) # 행 기준으로 결합
print(result1)
print(result1.shape)

# 결합이 불가 -> 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a, b), axis = 1) # ValueError  

c = np.array([[7],[8],[9]])
result3 = np.concatenate((result1, c), axis = 1) # 열 기준으로 결합
print(result3)
print(result3.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 7]
 [3 4 8]
 [5 6 9]]
(3, 3)


In [59]:
# np.stack()
# 새로운 차원을 추가하면서 결합

a = np.array([1,2,3])
b = np.array([4,5,6])

# axis = 0

s1 = np.stack((a, b), axis = 0)
print(s1)
print(s1.shape)

# axis = 1

s2 = np.stack((a, b), axis = 1)
print(s2)
print(s2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# hstack()
# - 열 방향(가로)로 결합

a = np.array([1,2,3])
b = np.array([4,5,6])

h = np.hstack((a, b))
print(h)

# vstack()
# - 행 방향(세로)로 결합
v = np.vstack((a, b))
print(v)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [68]:
# np.split()
# 배열을 여러개의 하위 배열로 분할

a = np.arange(9)
s = np.split(a, 3)

print(a)
print(s)
print(s[0])
print(s[1])
print(s[2])

# 같은 크기로만 나눌 수 있음
# s2 = np.split(a, 4) # ValueError -> 4로는 균일하고 나눌 수 없기 때문


[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [71]:
a = np.arange(16).reshape(4,4)
print(a)

s1 = np.split(a, [1, 3])
print(s1)
for part in s1:
    print(part)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


#### 실습 2. 배열의 결합과 분리(1)

In [ ]:
# 1. 다음 두 배열을 행 방향으로 이어붙이세요

a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
result = np.concatenate((a, b), axis = 0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [86]:
# 2. 아래 배열을 3개로 같은 크기로 분할하세요.

a = np.arange(12)
result = np.split(a, 3)
for part in result:
    print(part)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [87]:
# 3. 다음 배열들을 새로운 축에 쌓아 shape이 (3, 2)인 배열을 만드세요.

a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])

result = np.stack((a,b,c), axis = 0)
print(result)
print(result.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [82]:
# 4. shape가 (2, 3)인 아래 두 배열을 shape (2, 2, 3)인 3차원 배열을 만드세요.

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

result = np.stack((a, b), axis = 0)
print(result)
print(result.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
# 5.아래의 1차원 배열을 2:3:3 비율(총 3개)로 분할하세요.

arr= np.arange(8)

result = np.split(arr, [2, 5], axis = 0)
print(result)
for r in result:
    print(r)



[array([0, 1]), array([2, 3, 4]), array([5, 6, 7])]
[0 1]
[2 3 4]
[5 6 7]


In [85]:
# 6.아래 두 배열을 axis=0, axis=1로 각각 stack하여 두 경우의 결과 shape을 모두 구하세요

a = np.ones((2, 3))
b = np.zeros((2, 3))

stack0 = np.stack((a,b), axis = 0)
print("axis=0 결과 shape:", stack0.shape)
stack1 = np.stack((a,b), axis = 1)
print("axis=1 결과 shape:", stack1.shape)

axis=0 결과 shape: (2, 2, 3)
axis=1 결과 shape: (2, 2, 3)


### 3-3. 배열의 정렬

In [ ]:
# np.sort(array)
# 정렬된 복사본 반환
# array.sort()
# 원본 배열을 정렬

# 1차원 배열
a = np.array([3,1,4,2])

# 정렬한 배열을 반환
s = np.sort(a)
print(s)
print(a)

# 원본을 정렬
a.sort()
print(a)

# 내림차순 : sort한 후 배열을 뒤집어야 함
print(a[::-1])

[1 2 3 4]
[3 1 4 2]
[1 2 3 4]


In [90]:
# 2차원 배열 정렬
a = [[6,5,4], [3,1,2]]
s1 = np.sort(a, axis = 0)
print(s1)
s2 = np.sort(a, axis = 1)
print(s2)

[[3 1 2]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [91]:
# np.argsort()
# - 정렬 인덱스를 반환

a = np.array([3,5,1,2,4])
idx = np.argsort(a)
print(idx)
print(a[idx])

[2 3 0 4 1]
[1 2 3 4 5]


#### 실습 3. 배열의 정렬(1)

In [99]:
# 1. 아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요.

arr = np.array([7,2,9,4,5])
asc = np.sort(arr)
desc = np.sort(arr)[::-1]
print("오름차순:", asc)
print("내림차순:", desc)

오름차순: [2 4 5 7 9]
내림차순: [9 7 5 4 2]


In [ ]:
# 2. 아래의 2차원 배열에서 각 행별로 오름차순 정렬된 배열을 구하세요.

arr = np.array([[9,2,5],
                [3,8,1]])

result = np.sort(arr, axis = 1)
print(result)

[[2 5 9]
 [1 3 8]]


In [100]:
# 3. 아래의 1차원 배열에서 정렬 결과(오름차순)가 되는 인덱스 배열을 구하고,
# 그 인덱스를 이용해 원본 배열을 직접 재정렬하는 코드를 작성하세요

arr = np.array([10,3,7,1,9])
idx = np.argsort(arr)
s = arr[idx]
print(idx)
print(s)

[3 1 2 4 0]
[ 1  3  7  9 10]


In [ ]:
# 4. 아래 2차원 배열을 열 기준(axis = 0)으로 오름차순 정렬된 배열을 구하세요

arr = np.array([[4,7,2],
                [9,1,5],
                [6,8,3]])

result = np.sort(arr, axis = 0)
print(result)

[[4 1 2]
 [6 7 3]
 [9 8 5]]
