### PyTorch
- GPU를 이용한 동적 신경망 구축이 가능한 딥러닝 프레임워크

#### PyTorch의 구성 요소
- torch: 메인 네임스페이스, 텐서 등의 다양한 함수가 포함
- torch.autograd: 자동 미분 기능을 제공하는 라이브러리
- torch.nn: 신경망 구축을 위한 데이터 구조, 레이어 등으로 제공하는 라이브러리
- torch.multiprocessing: 병렬처리 기능을 제공하는 라이브러리
- torch.optim: SGD (확률적 경사 하강법)등 파라미터 최적화 알고리즘 제공
- torch.utils: 데이터 조작 등 유틸리티 기능 제공

#### 01. 텐서 (Tensor)
- 방향성과 크기를 동시에 표현하는 다차원 배열

In [11]:
import torch
import numpy as np

torch.__version__

'2.10.0+cpu'

#### 1-1. 텐서의 초기화
- 초기화: 텐서를 생성하고 특정 값을 (최초로) 채우는 것

초기화 되지 않은 텐서

In [3]:
x = torch.empty(4,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


#### 무작위로 초기화된 텐서
- rand: 0과 1 사이의 값으로 랜덤하게 초기화된 텐서 생성
- randn: 표준정규분포를 따를는 랜덤한 값으로 초기화

In [4]:
x = torch.rand(4, 2)
y = torch.randn(2, 3)

print(x)
print(y)

tensor([[0.1345, 0.6149],
        [0.5146, 0.8638],
        [0.4138, 0.4533],
        [0.2152, 0.8288]])
tensor([[ 0.2216, -0.3061, -1.3642],
        [-1.0603, -0.4871,  0.0861]])


#### 0으로 채워진 텐서

In [5]:
x = torch.zeros(4,2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


#### 1로 채워진 텐서

In [8]:
x = torch.ones(2,4, dtype=torch.double)
print(x)

# 기존 텐서의 속성 (데이터 타입, 장치)을 물려받음
y = x.new_ones(3,2)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


#### 사용자가 입력한 값으로 텐서 초기화

In [9]:
x = torch.tensor([1,2.5])
print(x)

tensor([1.0000, 2.5000])


#### numpy에서 불러오기

In [12]:
data = [1,2,3,4]
np_array = np.array(data)
x = torch.from_numpy(np_array)
print(x)

tensor([1, 2, 3, 4])


#### _like 메서드
- 기존 텐서의 속성을 복사하면서 값만 다른 텐서를 만드는 메서드

In [13]:
x = torch.tensor([[1,2], [3,4]], dtype=torch.float64)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


#### 1-2 텐서의 속성

In [14]:
t = torch.rand(3,4)
print(t.size()) # 모양
print(t.shape) # 모양
print(t.dtype) # 자료형
print(t.device) # 장치

torch.Size([3, 4])
torch.Size([3, 4])
torch.float32
cpu


#### 1-3. 데이터 타입
##### 특정 데이터 타입의 텐서 생성

In [15]:
x = torch.FloatTensor([1,2,3])
print(x.dtype)

y = torch.tensor([1,2,3], dtype=torch.float32)
print(y.dtype)

torch.float32
torch.float32


#### 타입 캐스팅(형 변환)


In [17]:
x = torch.FloatTensor([1.1,2.2,3.3])
print(x)
print(x.short())
print(x.int())
print(x.long())

y = torch.IntTensor([1,2,3])
print(y)
print(y.half())
print(y.float())
print(y.double())

tensor([1.1000, 2.2000, 3.3000])
tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.], dtype=torch.float16)
tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


#### 1-4. 다차원 텐셔 표현
##### 0D Tensor(Scalar)
- 하나의 숫자를 담고 있는 텐서
- 축과 형상이 없음

In [18]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


#### 1D Tensor(Vector)
- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [19]:
t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)


1
torch.Size([3])
tensor([1, 2, 3])


#### 2D Tensor(Matrix)
- 행렬과 같은 모양으로 두 개의 축이 존재
- 일반적인 수치, 통계 데이터셋에 주로 활용

In [20]:
t2 = torch.tensor([[1,2,3],
                [1,2,3,],
                [1,2,3]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])


#### 3D Tensor
- 큐브와 같은 모양으로 세 개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간축이 포함된 시계열 데이터에 해당
- ex) 주식 가격, 질병 발병 데이터

In [21]:
t3 = torch.tensor([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([2, 3, 3])
tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]])


#### 4D Tensor
- 4개의 축
- 컬러 이미지가 대표적인 사례
- 주로 샘플, 높이, 너비, 컬러 채널을 가진 구조로 사용

In [22]:
t4 = torch.tensor([[[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]],
                [[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]])

print(t4.ndim)
print(t4.shape)
print(t4)

4
torch.Size([2, 2, 3, 3])
tensor([[[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]],


        [[[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]],

         [[1, 2, 3],
          [1, 2, 3],
          [1, 2, 3]]]])


#### 5D Tensor
- 5개의 축
- 비디오 데이터가 대표적 사례
- 주로 샘플, 프레임, 높이, 너비, 컬러 채널을 가진 구조로 사용

In [26]:
t5 = torch.tensor([[[[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]],
                [[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]]]])

print(t5.ndim)
print(t5.shape)
print(t5)

5
torch.Size([1, 2, 2, 3, 3])
tensor([[[[[1, 2, 3],
           [1, 2, 3],
           [1, 2, 3]],

          [[1, 2, 3],
           [1, 2, 3],
           [1, 2, 3]]],


         [[[1, 2, 3],
           [1, 2, 3],
           [1, 2, 3]],

          [[1, 2, 3],
           [1, 2, 3],
           [1, 2, 3]]]]])
