### 03. 텐서의 조작

In [2]:
import torch

#### 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [ ]:
x = torch.tensor([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(x[1,1]) # tensor(5)
print(x[2,0]) # tensor(7)
print(x[0,:]) # tensor([1, 2, 3])
print(x[:,2]) # tensor([3, 6, 9])
print(x[[0,1,2], [0,1,2]]) # tensor([1, 5, 9]) -> fancy 인덱싱
print(x[x > 5]) # tensor([6, 7, 8, 9]) -> boolean 인덱싱 

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [ ]:
x = torch.tensor([10, 20, 30, 40, 50])

x[0] = 100
print(x) # tensor([100,  20,  30,  40,  50])

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200, 300, 400])
print(x) # tensor([100, 200, 300, 400,  50])

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


#### 3-2. 텐서의 크기, 모양 변경

In [7]:
x = torch.rand(4,5)
print(x)
y = x.view(20)
print(y)
z = y.view(5,-1) # -1 -> 자동 계산
print(z)

n=z.view(2, 2, 5)
print(n)

tensor([[0.0240, 0.7929, 0.7273, 0.0363, 0.9354],
        [0.7239, 0.4407, 0.9488, 0.9742, 0.7968],
        [0.8770, 0.3482, 0.8018, 0.2518, 0.1940],
        [0.5493, 0.4944, 0.7144, 0.2187, 0.6439]])
tensor([0.0240, 0.7929, 0.7273, 0.0363, 0.9354, 0.7239, 0.4407, 0.9488, 0.9742,
        0.7968, 0.8770, 0.3482, 0.8018, 0.2518, 0.1940, 0.5493, 0.4944, 0.7144,
        0.2187, 0.6439])
tensor([[0.0240, 0.7929, 0.7273, 0.0363],
        [0.9354, 0.7239, 0.4407, 0.9488],
        [0.9742, 0.7968, 0.8770, 0.3482],
        [0.8018, 0.2518, 0.1940, 0.5493],
        [0.4944, 0.7144, 0.2187, 0.6439]])
tensor([[[0.0240, 0.7929, 0.7273, 0.0363, 0.9354],
         [0.7239, 0.4407, 0.9488, 0.9742, 0.7968]],

        [[0.8770, 0.3482, 0.8018, 0.2518, 0.1940],
         [0.5493, 0.4944, 0.7144, 0.2187, 0.6439]]])


#### 3-3. 텐서의 숫자값 얻기
- tensor.item(): 스칼라 값 하나만 존재해야 사용 가능

In [10]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.1534, 0.0562])
tensor(0.1534)
0.15342485904693604


#### 3-4. 차원 축소 및 증가
##### 차원 축소 (제거)
- torch.squeeze(): 크기가 1인 차원을 제거함

In [14]:
t = torch.rand(3,1,3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.1929, 0.2449, 0.4633]],

        [[0.1806, 0.7272, 0.0339]],

        [[0.2581, 0.2724, 0.1586]]])
torch.Size([3, 1, 3])
tensor([[0.1929, 0.2449, 0.4633],
        [0.1806, 0.7272, 0.0339],
        [0.2581, 0.2724, 0.1586]])
torch.Size([3, 3])


#### 차원 증가(생성)
- torch.ynsqueezze(): dim 설정에 따라 차원을 증가시킴
    - dim은 하나의 차원이 추가되는 인덱스

In [17]:
t = torch.rand(3, 3, 3)
print(t.shape)

# 0 가장 상위 차원 -> 3 가장 하위 차원
ts1 = torch.unsqueeze(t, dim=0)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3)
print(ts4.shape)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


#### 3-5. 텐서간 결합
- torch.stack(): 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원 생성됨

In [19]:
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
result = torch.stack([x,y,z])
print(result)

a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[5,6], [7,8]])
result2 = torch.stack([a,b])
print(result2)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- torch.cat(): 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성X

In [21]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[7,8], [9,10]])

result = torch.cat((a,b), dim=1)
print(result)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


#### 3-6 텐서 나누기
- torch.chunk(): 텐서를 지정한 개수에 따라 나눔
    - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐
- torch.split(): 지정한 사이즈에 따라 나눔
    - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐

In [22]:
t = torch.rand(3, 7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.3804, 0.5638, 0.1546, 0.1244, 0.4602, 0.8696, 0.3136],
        [0.8621, 0.6111, 0.8386, 0.1706, 0.9169, 0.3183, 0.5474],
        [0.0632, 0.8546, 0.8075, 0.5797, 0.4031, 0.5822, 0.3917]])
tensor([[0.3804, 0.5638, 0.1546],
        [0.8621, 0.6111, 0.8386],
        [0.0632, 0.8546, 0.8075]])
tensor([[0.1244, 0.4602, 0.8696],
        [0.1706, 0.9169, 0.3183],
        [0.5797, 0.4031, 0.5822]])
tensor([[0.3136],
        [0.5474],
        [0.3917]])


In [23]:
t = torch.rand(3, 7)
print(t)

# 쪼갤 열의 개수 지정
t1,t2,t3 = torch.split(t, [2, 3, 2], dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.6504, 0.4931, 0.8677, 0.1281, 0.5109, 0.1806, 0.4192],
        [0.8634, 0.0259, 0.5166, 0.4308, 0.5803, 0.0035, 0.9606],
        [0.5240, 0.4738, 0.5026, 0.4280, 0.1670, 0.7423, 0.2700]])
tensor([[0.6504, 0.4931],
        [0.8634, 0.0259],
        [0.5240, 0.4738]])
tensor([[0.8677, 0.1281, 0.5109],
        [0.5166, 0.4308, 0.5803],
        [0.5026, 0.4280, 0.1670]])
tensor([[0.1806, 0.4192],
        [0.0035, 0.9606],
        [0.7423, 0.2700]])
